### PR TITLE
feat: Baconian Cipher

### PR DESCRIPTION
**Pull request by Iqrar99**
This PR is intended for enhancement. We add a new cipher to enrich the cipher library in this repo.

### CODE REVIEW

**Comment by Iqrar99** [comment]
The logic has been implemented. These are the examples use of **Baconian Chiper**.
## Common use
### Encode
image

image

image

### Decode
image

image


## Error handling
### Encode
image

image

### Decode
image

image

image

---

Let me know if there is something that I need to fix or improve in the code.

**Comment by marvhus** [comment]
@Iqrar99 

Good work :+1:

I'll take a look at it tomorrow.

**Review by marvhus — APPROVED** [review]
Hi. It seams like there might be an issue in the cipher implenetation.
I tried the same input on cryptex and [decode.fr](https://www.dcode.fr/bacon-cipher) and I got slightly different results.
Cryptex:
image
Decode.fr:
image

Cryptex:   AABBBAABAAABABBABABBABBBABABBAABBBABAAABABABBAAABB
Decode.fr: AABBBAABAAABABAABABAABBABBABAAABBABBAAAAABABAAAABB

(Note: I'm not sure if I'm doing something wrong, but I think there shouldn't be a difference, but if I am doing something wrong, please tell me)

**Review by marvhus — CHANGES_REQUESTED** [review]
sorry I meant to request changes, I pressed the wrong button

**Comment by Iqrar99** [comment]
Hello, you are not doing wrong actuallly. the [decode.fr](https://www.dcode.fr/bacon-cipher) Actually uses the first variant of the Baconian Cipher where the I and J has the same code, also U and V has the same code.

image

In my commits, I'm using the second variant where each alphabets has unique code.
image

**Comment by marvhus** [comment]
> Hello, you are not doing wrong actuallly. the [decode.fr](https://www.dcode.fr/bacon-cipher) Actually uses the first variant of the Baconian Cipher where the I and J has the same code, also U and V has the same code.
> 
> image
> 
> In my commits, I'm using the second variant where each alphabets has unique code. image

ah ok, if it is intentional I'll approve it

**Review by marvhus — APPROVED** [review]
:+1: Good work :+1:

**Comment by marvhus** [comment]
adds another cipher to #1

**Pull request merged**
