### PR TITLE
Added the ability to chain layers

### LINKED ISSUE #23: Encryption Layering / chaining
One big feature of the previous version was encryption layering. 
So the syntax was something to tune of: 

`cryptex b64 -e -t "Hello Code! " + hex -e`

Would output the encryption made in base64 which then encoded to hex.
So it would look like: 

image

only obviously its one command instead of two. Cutting out the middle man or men. The magic was we were able to chain multiple encryptions together one one command to produce some really cool results.

### PR DESCRIPTION
**Pull request by ahmedheltaher**
I have left some print statements i was using to  debug, if this PR will be merged i will add more commit to remove them.

Good Luck and sorry for that messy code

closes #23

### CODE REVIEW

**Comment by marvhus** [comment]
im gonna look at it later when I have time

**Review by marvhus — CHANGES_REQUESTED** [review]
It works, but when layering ciphers the input field on the output shows the input from the last layer instead of showing what your originally inputted.

Example: `python3 src/main.py cc -e -t 'hello' -k 3 + l33t -e`
image

Also, it would be nice if when you only enter the short name for a cipher and no arguments it would show the help menu for that cipher, instead of the text it shows now.
Example: `python3 src/main.py cc -e -t 'hello' -k 3 + l33t`
image
(note: the -h argument it suggests is for the whole program, not the specific cipher)

Also, I'm not sure if the path (`./src/main.py`) to do this would work in the future where people most likely will have an alias for running cryptex (see the install script), so a way to prevent that would be using `CRYPTEX_PATH` environment variable (see the install script). 
Although a better way would to do this using python instead of making sub processes.

**Comment by ahmedheltaher** [comment]
Ok i will work on those changes later today and get back to you

**Comment by AlexKollar** [comment]
> Ok i will work on those changes later today and get back to you 

Can't wait to see!
I also took the liberty of reaching out on discord. Just to say hi!

**Comment by ahmedheltaher** [comment]
Screenshot_20221013_055859

is this how you want to handle the case of no arguments supplied.
ignore the other random prints

**Comment by ahmedheltaher** [comment]
After some thoughts, I think if we tweaked the main class to accept the list of and evaluate them internally instead of makeing it call it the script it would make the code more robust and better in terms of portability and simplicity if you are ok with that i can work on it later on today after i get back from the university.

If you are going to go with this idea please let me know first if the logic is alright

Thank you

**Comment by marvhus** [comment]
> After some thoughts, I think if we tweaked the main class to accept the list and evaluate them internally instead of makeing it call it the script it would make the code more robust and better in terms of portability and simplicity if you are ok with that i can work on it later on today after i get back from the university.
> 
> If you are going to go with this idea please let me know first if the logic is alright
> 
> Thank you

Making it run within python would be nice, and most of it is already set up.
(Check the cipher_list variable for more context)

**Comment by marvhus** [comment]
> Screenshot_20221013_055859
> 
> is this how you want to handle the case of no arguments supplied. ignore the other random prints

Yeah

**Comment by marvhus** [comment]
> > After some thoughts, I think if we tweaked the main class to accept the list and evaluate them internally instead of makeing it call it the script it would make the code more robust and better in terms of portability and simplicity if you are ok with that i can work on it later on today after i get back from the university.
> > If you are going to go with this idea please let me know first if the logic is alright
> > Thank you
> 
> Making it run within python would be nice, and most of it is already set up. (Check the cipher_list variable for more context)

also if you do it that way, I think it would be easier to make sure the output has the right input/output without having to use external text files

**Comment by ahmedheltaher** [comment]
> > > After some thoughts, I think if we tweaked the main class to accept the list and evaluate them internally instead of makeing it call it the script it would make the code more robust and better in terms of portability and simplicity if you are ok with that i can work on it later on today after i get back from the university.
> > > If you are going to go with this idea please let me know first if the logic is alright
> > > Thank you
> > 
> > Making it run within python would be nice, and most of it is already set up. (Check the cipher_list variable for more context)
> 
> also if you do it that way, I think it would be easier to make sure the output has the right input/output without having to use external text files

Ok when I get back i will start working on it

**Comment by ahmedheltaher** [comment]
Check out the new commit the new `controller.py` might need a little clean up but it is ok for now

**Comment by marvhus** [comment]
@ahmedheltaher I tried running the main file to test if it works... and I got an error
```
$ python3 src/main.py

Traceback (most recent call last):
  File "src/main.py", line 2, in <module>
    from controller import Controller
  File "/home/martin/src/py/Cryptex/layering/src/controller.py", line 85, in <module>
    class ArgumentParser:
  File "/home/martin/src/py/Cryptex/layering/src/controller.py", line 112, in ArgumentParser
    def parse_string(self, string: list[str]) -> argparse.Namespace:
TypeError: 'type' object is not subscriptable
```

**Comment by ahmedheltaher** [comment]
Ok i will take a look in one hour

**Review by marvhus — CHANGES_REQUESTED** [review]
Hi, there seams like there is a bug where the output includes quotation marks for some reason, and those are factored into the next cipher after it:
image

image

image

image

image

image

**Review by marvhus — APPROVED** [review]
Everything seams to be working, so I'll merge it

:+1: Good job :+1:

**Comment by ahmedheltaher** [comment]
> Everything seams to be working, so I'll merge it
> 
> +1 Good job +1



thank You, and sorry for the latency

**Comment by marvhus** [comment]
> > Everything seams to be working, so I'll merge it
> > +1 Good job +1
> 
> thank You, and sorry for the latency

No problem.

Now I just have to figure how to resolve these merge conflicts

**Comment by ahmedheltaher** [comment]
You can just delete all the highlighted lines and it should be enough

**Comment by ahmedheltaher** [comment]
I Can do it if you allow me

**Comment by marvhus** [comment]
> You can just delete all the highlighted lines and it should be enough

I think I'll approve everything that you changed, then add things bag if they are needed

**Comment by ahmedheltaher** [comment]
> > You can just delete all the highlighted lines and it should be enough
> 
> I think I'll approve everything that you changed, then add things bag if they are needed

Ok Good Luck

**Pull request merged**
