### PR TITLE
Autokey cipher

### LINKED ISSUE #40: Autokey Cipher
Hello, I would like to add autokey cipher to the list of ciphers. I believe that it is an important cipher to have since it is more secure than vignere cipher since vignere has limited key. Can you assign this to me? https://en.wikipedia.org/wiki/Autokey_cipher

### PR DESCRIPTION
**Pull request by nga1hte**
This pull request resolves #40

### CODE REVIEW

**Review by marvhus — APPROVED** [review]
:+1: Good job :+1: 

Thanks for the addition.

**Comment by marvhus** [comment]
adds another cipher to #1

**Comment by nga1hte** [comment]
@marvhus since playfair is already assigned to someone, I am unclear to what Pin Buster is. Can i get more information to what exactly it does? Is it a ciphering algorithm?

**Comment by AlexKollar** [comment]
> @marvhus since playfair is already assigned to someone, I am unclear to what Pin Buster is. Can i get more information to what exactly it does? Is it a ciphering algorithm?

Okay so pin buster is meant to be a 4 - 8 digit pin breaking algorithm. So it would take a file with a pin inside of it and iterate through the numbers on it till it decodes the pin inside.  I think @GamerChillz can elaborate better as its his idea. He is the one who comes up with the whacky encryption ideas like our static encryption.  

Think how do we crack a safe with software was supposed to be the idea behind it. 
Again not that any of us would but that is the notion.

**Comment by marvhus** [comment]
> > @marvhus since playfair is already assigned to someone, I am unclear to what Pin Buster is. Can i get more information to what exactly it does? Is it a ciphering algorithm?
> 
> Okay so pin buster is meant to be a 4 - 8 digit pin breaking algorithm. So it would take a file with a pin inside of it and iterate through the numbers on it till it decodes the pin inside.  I think @GamerChillz can elaborate better as its his idea. He is the one who comes up with the whacky encryption ideas like our static encryption.  
> 
> Think how do we crack a safe with software was supposed to be the idea behind it. 
> Again not that any of us would but that is the notion. 

At tbis point I don't reallu understand the point of it. Should we just remove it?

**Pull request merged**
