### PR TITLE
Add input and output function

### PR DESCRIPTION
**Pull request by IamMU**
add ability to use files for encoding and decoding. 
Sample commands:
   ```bash
cryptex b64 -e -i input.txt -o output.txt
```
   ```bash
cryptex b64 -d -i output.txt -o output-decoded.txt
```

### CODE REVIEW

**Comment by marvhus** [comment]
It works on my side.

Though @IamMU could you add some formatting to the 
"Wrote output to f"{args.output}!" and f"Opened {args.input}" strings.
Maybe add them to the list of things under the input and output things.
For example:
```
               _____              __
              / ___/_____ _____  / /______ __
             / /__/ __/ // / _ \/ __/ -_) \ /
             \___/_/  \_, / .__/\__/\__/_\_\
              V:0.0.1/___/_/  OOP Edition
              Locks only exist to keep honest
                       people honest

        ------ Cipher: b64 -- Mode: Encode ------
        Input      | hello, world!
        output     | aGVsbG8sIHdvcmxkIQo=

        Read File  | {args.input}
        Wrote File | {args.output}
        ----
```

**Review by marvhus — CHANGES_REQUESTED** [review]
Works fine, bot add some formatting like I said in my comment

**Comment by IamMU** [comment]
working on it

**Review by marvhus — CHANGES_REQUESTED** [review]
could you move the print statements inside the print statement above.
For example:
```
        print(
        f'''
        ------ Cipher: {args.cipher} -- Mode: {mode} ------
        Input      | {args.text}
        Output     | {out['text']}

        Read File  | {args.input if args.input else "N/A"}
        Wrote File | {args.output if args.output else "N/A"}
        ''')
```

**Review by marvhus — APPROVED** [review]
Great work @IamMU

**Pull request merged**
