### PR TITLE
Added Multiplicative Cipher

### LINKED ISSUE #10: Multiplicative Cipher

### PR DESCRIPTION
**Pull request by ahmedheltaher**
closes #10

### CODE REVIEW

**Comment by marvhus** [comment]
Could you add the cipher to `src/cipher/ciphers/__init__.py`.
And I'll look at it later today.

**Comment by ahmedheltaher** [comment]
Yah, Sure I totally forgot about that, Iwill do It Now

**Comment by marvhus** [comment]
I'll look into it and see if I can fix it

**Comment by marvhus** [comment]
I found the bug

you need to validate the user input (key) before using it, and converting it to int

**Comment by ahmedheltaher** [comment]
Ok i will Handel it just hive me 20 mins

**Comment by marvhus** [comment]
> Ok i will Handel it just hive me 20 mins

I already fixed it, I'll push my fix if that is ok

**Comment by ahmedheltaher** [comment]
Yah, sure no problem, thank you

**Comment by marvhus** [comment]
The only issue now is that I think it provides the wrong output

What I got:
image

What I expected:
image

https://www.dcode.fr/multiplicative-cipher

Am I doing something wrong? or is there something wrong?

**Comment by marvhus** [comment]
it doesn't convert the uppercase letters

**Comment by marvhus** [comment]
Should we just force everything to be lowecase? or should we see if there is a fix?

**Comment by marvhus** [comment]
I think I found a fix

**Comment by marvhus** [comment]
I fixed it

**Comment by ahmedheltaher** [comment]
Sorry for rushing on my tests.
Good Job

**Comment by ahmedheltaher** [comment]
What was the solution

**Comment by marvhus** [comment]
> What was the solution

you can look at the commit if you want the code.

but it was basically just adding uppercase letters to the dict with an offset of 26
so 0-25 is lowercase, and 26 - 52 is uppercase
and it then just applies that offset to the new index if the char is uppercase

**Comment by ahmedheltaher** [comment]
Thank you so much

and sorry one more time for rushing.
Good Luck

**Comment by marvhus** [comment]
> Thank you so much
> 
> and sorry one more time for rushing. Good Luck

no problem.

Btw, you are wellcome to contine contributing to Cryptex.

**Comment by ahmedheltaher** [comment]
Yah for sure i will.

Good Luck Guys

**Comment by marvhus** [comment]
btw, if you want to come chat with us there is a link to our discord in README.md

**Pull request merged**
